[project]
name = "pipal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mo Bashiri", email = "mohammadbashiri93@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "rich>=14.3.3",
]

[project.scripts]
pipal = "pipal.cli:main"

[build-system]
requires = ["uv_build>=0.9.16,<0.10.0"]
build-backend = "uv_build"
